#!/bin/bash
# This script was auto-generated by analyser3.py to automate the project workflow.
# It runs all simulations and then performs the analysis.

echo "--- [WORKFLOW START] ---"

echo ">>> Running Part A Simulations (DropTail)..."
echo "   -> Running partA/cubicCode.tcl"
ns partA/cubicCode.tcl
echo "   -> Running partA/renoCode.tcl"
ns partA/renoCode.tcl
echo "   -> Running partA/vegasCode.tcl"
ns partA/vegasCode.tcl
echo "   -> Running partA/yeahCode.tcl"
ns partA/yeahCode.tcl

echo ">>> Running Part B Simulations (RED)..."
echo "   -> Running partB/cubicCode.tcl"
ns partB/cubicCode.tcl
echo "   -> Running partB/renoCode.tcl"
ns partB/renoCode.tcl
echo "   -> Running partB/vegasCode.tcl"
ns partB/vegasCode.tcl
echo "   -> Running partB/yeahCode.tcl"
ns partB/yeahCode.tcl

echo ">>> Running Part C Simulations (Reproducibility)..."
for i in {1..5}
do
    echo "   -> Running partC/cubicCodePartC.tcl with seed $i"
    ns partC/cubicCodePartC.tcl $i
done

echo ">>> All simulations complete. Running analysis script..."
python3.7 analyser3.py

echo "--- [WORKFLOW COMPLETE] ---"